### ISSUE TITLE
Compilation issues for bra regarding yampi

### ISSUE THREAD

**Issue by Line-fr** [naoki-yoshioka/yampi#123]
```
mkdir -p build/
mpiCC -I./include -I./../ket/include -I./../yampi/include -I./../cxxopts/include -I./../fmt/include -DKET_PRINT_LOG -DKET_USE_OPENMP -DKET_USE_DIAGONAL_LOOP -DKET_USE_BARRIER -DNDEBUG -fopenmp -std=c++17 -Wall -Ofast  -c src/adj_controlled_not.cpp -o build/adj_controlled_not.o
In file included from ./../yampi/include/yampi/bounds.hpp:10,
                 from ./../yampi/include/yampi/datatype.hpp:18,
                 from ./include/bra/state.hpp:25,
                 from ./include/bra/gate/gate.hpp:7,
                 from src/adj_controlled_not.cpp:9:
./../yampi/include/yampi/extent.hpp:42:24: error: ‘constexpr yampi::extent::extent(const MPI_Count&)’ cannot be overloaded with ‘constexpr yampi::extent::extent(const MPI_Aint&)’
   42 |     explicit constexpr extent(MPI_Count const& mpi_extent)
      |                        ^~~~~~
./../yampi/include/yampi/extent.hpp:38:24: note: previous declaration ‘constexpr yampi::extent::extent(const MPI_Aint&)’
   38 |     explicit constexpr extent(MPI_Aint const& mpi_extent) noexcept
      |                        ^~~~~~
In file included from ./../yampi/include/yampi/communicator_base.hpp:17,
                 from ./../yampi/include/yampi/communicator.hpp:11,
                 from ./include/bra/state.hpp:27,
                 from ./include/bra/gate/gate.hpp:7,
                 from src/adj_controlled_not.cpp:9:
./../yampi/include/yampi/information.hpp: In member function ‘boost::optional<std::__cxx11::basic_string<char> > yampi::information::at(const string&, const yampi::environment&) const’:
./../yampi/include/yampi/information.hpp:187:13: error: invalid conversion from ‘int’ to ‘int*’ [-fpermissive]
  187 |             buffer_length, const_cast<char*>(result.c_str()), std::addressof(flag));
      |             ^~~~~~~~~~~~~
      |             |
      |             int
In file included from /usr/include/x86_64-linux-gnu/mpich/mpi.h:977,
                 from ./../yampi/include/yampi/allocator.hpp:12,
                 from ./include/bra/state.hpp:24,
                 from ./include/bra/gate/gate.hpp:7,
                 from src/adj_controlled_not.cpp:9:
/usr/include/x86_64-linux-gnu/mpich/mpi_proto.h:463:62: note:   initializing argument 3 of ‘int MPI_Info_get_string(MPI_Info, const char*, int*, char*, int*)’
  463 | int MPI_Info_get_string(MPI_Info info, const char *key, int *buflen, char *value, int *flag)
      |                                                         ~~~~~^~~~~~
make: *** [Makefile:180: build/adj_controlled_not.o] Error 1
```

for it to compile, I add "&" in front of buffer_length and I commented the function under line 42 of extent.hpp
But I don't know if that was the right thing to do

I use a fresh ubuntu wsl install

**Comment by Line-fr** [comment]
```
In file included from ./../yampi/include/yampi/all_reduce.hpp:14,
                 from ./../yampi/include/yampi/lowest_io_process.hpp:13,
                 from ./../ket/include/ket/mpi/utility/logger.hpp:21,
                 from ./../ket/include/ket/mpi/utility/simple_mpi.hpp:47,
                 from ./include/bra/simple_mpi_state.hpp:9,
                 from src/make_simple_mpi_state.cpp:10:
./../yampi/include/yampi/binary_operation.hpp: In member function ‘void yampi::binary_operation::reset(void (*)(void*, void*, int*, MPI_Datatype*), bool, const yampi::environment&)’:
./../yampi/include/yampi/binary_operation.hpp:246:24: error: invalid conversion from ‘void (*)(void*, void*, int*, MPI_Datatype*)’ {aka ‘void (*)(void*, void*, int*, int*)’} to ‘void (*)(void*, void*, MPI_Count*, MPI_Datatype*)’ {aka ‘void (*)(void*, void*, long int*, int*)’} [-fpermissive]
  246 |       mpi_op_ = create(mpi_user_function, is_commutative, environment);
      |                        ^~~~~~~~~~~~~~~~~
      |                        |
      |                        void (*)(void*, void*, int*, MPI_Datatype*) {aka void (*)(void*, void*, int*, int*)}
./../yampi/include/yampi/binary_operation.hpp:169:28: note:   initializing argument 1 of ‘MPI_Op yampi::binary_operation::create(void (*)(void*, void*, MPI_Count*, MPI_Datatype*), bool, const yampi::environment&) const’
  169 |       MPI_User_function_c* mpi_user_function, bool const is_commutative,
      |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
make: *** [Makefile:180: build/make_simple_mpi_state.o] Error 1
```

another one, I should tell that I m with mpich 4.0

This one took me more time but I figured replacing MPI_User_function with MPI_User_function_c at line 242 seems to have solved it

**Comment by Line-fr** [comment]
this one too
```
./../yampi/include/yampi/algorithm/transform.hpp:168:54: error: no matching function for call to ‘std::vector<double, yampi::allocator<double> >::vector(const yampi::count&)’
  168 |       std::vector<Value, ::yampi::allocator<Value> > transform_buffer(send_buffer.count());
```

To fix it, I had to replace in transform a lot of buffer.count() with bfuffer.count().mpi_count()

I don't know if that was the correct way of doing it but the problem seemed to be that the compiler did not know how to cast the count into an integer for the vector so I added this to fix the issue after exploring count.hpp

**Comment by Line-fr** [comment]
And after all this, I got bra to compile, or.. I think so?

**Comment by naoki-yoshioka** [comment]
Thank you for creating an issue!

> ```
> ./../yampi/include/yampi/extent.hpp:42:24: error: ‘constexpr yampi::extent::extent(const MPI_Count&)’ cannot be overloaded with ‘constexpr yampi::extent::extent(const MPI_Aint&)’
>    42 |     explicit constexpr extent(MPI_Count const& mpi_extent)
>       |                        ^~~~~~
> ./../yampi/include/yampi/extent.hpp:38:24: note: previous declaration ‘constexpr yampi::extent::extent(const MPI_Aint&)’
>    38 |     explicit constexpr extent(MPI_Aint const& mpi_extent) noexcept
>       |                        ^~~~~~
> ```

> ```
> ./../yampi/include/yampi/binary_operation.hpp:246:24: error: invalid conversion from ‘void (*)(void*, void*, int*, MPI_Datatype*)’ {aka ‘void (*)(void*, void*, int*, int*)’} to ‘void (*)(void*, void*, MPI_Count*, MPI_Datatype*)’ {aka ‘void (*)(void*, void*, long int*, int*)’} [-fpermissive]
>   246 |       mpi_op_ = create(mpi_user_function, is_commutative, environment);
>       |                        ^~~~~~~~~~~~~~~~~
>       |                        |
>       |                        void (*)(void*, void*, int*, MPI_Datatype*) {aka void (*)(void*, void*, int*, int*)}
> ./../yampi/include/yampi/binary_operation.hpp:169:28: note:   initializing argument 1 of ‘MPI_Op yampi::binary_operation::create(void (*)(void*, void*, MPI_Count*, MPI_Datatype*), bool, const yampi::environment&) const’
>   169 |       MPI_User_function_c* mpi_user_function, bool const is_commutative,
>       |       ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
> ```

> ```
> ./../yampi/include/yampi/algorithm/transform.hpp:168:54: error: no matching function for call to ‘std::vector<double, yampi::allocator<double> >::vector(const yampi::count&)’
>   168 |       std::vector<Value, ::yampi::allocator<Value> > transform_buffer(send_buffer.count());
> ```

These are bugs created when I modify to support MPI-4. Unfortunately I have no MPI-4 environment, so I haven't checked the MPI-4 version of my yampi works correctly.

> ```
> ./../yampi/include/yampi/information.hpp:187:13: error: invalid conversion from ‘int’ to ‘int*’ [-fpermissive]
>   187 |             buffer_length, const_cast<char*>(result.c_str()), std::addressof(flag));
>       |             ^~~~~~~~~~~~~
>       |             |
>       |             int
> ```

This is obviously a bug. I have no idea why I didn't find this bug...

I have pushed the bugfix branch https://github.com/naoki-yoshioka/yampi/tree/bugfix to the yampi repository. I hope this solves the issue.

Could you clone yampi, switch to bugfix, and check bra can be build if including the yampi-bugfix? You can prepare yampi-bugfix as follows:

```
$ git clone git@github.com:naoki-yoshioka/yampi.git
$ cd yampi
$ git switch bugfix
```

Then, modify the `YAMPI_DIR = ...` line in the `Makefile` file on the `bra` directory to specify the yampi-bugfix directory.

**Comment by Line-fr** [comment]
here is what I got now:

```
mpiCC -I./include -I./../ket/include -I./../yampifix/include -I./../cxxopts/include -I./../fmt/include -DKET_PRINT_LOG -DKET_USE_OPENMP -DKET_USE_DIAGONAL_LOOP -DKET_USE_BARRIER -DNDEBUG -fopenmp -std=c++17 -Wall -Ofast  -c src/adj_controlled_not.cpp -o build/adj_controlled_not.o
In file included from ./../yampifix/include/yampi/bounds.hpp:10,
                 from ./../yampifix/include/yampi/datatype.hpp:18,
                 from ./include/bra/state.hpp:25,
                 from ./include/bra/gate/gate.hpp:7,
                 from src/adj_controlled_not.cpp:9:
./../yampifix/include/yampi/extent.hpp:38:15: error: ‘std::enable_if<false, bool>::type’ has not been declared
   38 |     template <std::enable_if<not std::is_same<MPI_Aint, MPI_Count>::value, bool>::type = true>
      |               ^~~
make: *** [Makefile:180: build/adj_controlled_not.o] Error 1
```

this time I did not search into the code how to fix it

**Comment by Line-fr** [comment]
Yes it works now! thank you for the fix
